Fix wrong calculation of data_buffer_pointer of transfer::Normal
rust-osdev/xhci pull request #154
Opened 2023-07-17 14:46 UTC by lemolatoon

As defined in xHCI Specification [6.4.1.1 Normal TRB](https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/extensible-host-controler-interface-usb-xhci.pdf#page=465) , `Normal TRB`'s first 32bit is `Data Buffer Pointer Lo`, and next 32bit is `Data Buffer Pointer Hi`.

Before this patch, the calculation of `Data Buffer Pointer` in Normal TRB is wrong. So I fixed it.

Thank you.

2023-07-18 02:10 UTC, lemolatoon commented
```
error: lint `unaligned_references` has been removed: converted into hard error, see issue #82523 <https://github.com/rust-lang/rust/issues/82523> for more information
  --> src/lib.rs:51:5
   |
51 |     unaligned_references,
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
```
This lint error does not originate from this pull request. Is it preferable to fix this lint error also in this pull request?

2023-07-18 02:13 UTC, toku-sa-n commented
> ```
> error: lint `unaligned_references` has been removed: converted into hard error, see issue #82523 <https://github.com/rust-lang/rust/issues/82523> for more information
>   --> src/lib.rs:51:5
>    |
> 51 |     unaligned_references,
>    |     ^^^^^^^^^^^^^^^^^^^^
>    |
>    = note: `-D renamed-and-removed-lints` implied by `-D warnings`
> ```
> 
> This lint error does not originate from this pull request. Is it preferable to fix this lint error also in this pull request?

I'll fix it in another PR. Sorry, but please wait for it.

2023-07-18 07:47 UTC, toku-sa-n commented
@lemolatoon Sorry, but please wait more time because passing the Clippy action is not completed yet due to [a problem with the action itself](https://github.com/actions-rs/clippy-check/issues/2#issuecomment-1625977023).

2023-07-18 09:15 UTC, lemolatoon commented
I understand.

Thank you for maintaining this great crate! I am really helped.

2023-07-19 11:55 UTC, toku-sa-n commented
Thank you for waiting. Could you update the branch?

2023-07-19 11:57 UTC, toku-sa-n requested changes

2023-07-19 11:57 UTC, toku-sa-n commented on src/ring/trb/transfer.rs
> +    }
Could you split the test into two, one for Normal and the other for Isoch?

2023-07-19 12:04 UTC, lemolatoon commented on src/ring/trb/transfer.rs
> +    }
fixed

2023-07-19 12:09 UTC, merged

2023-07-19 12:10 UTC, toku-sa-n commented
Thank you! I'll upload a new version soon.

2023-07-19 12:17 UTC, toku-sa-n commented
Published as 0.9.2.